import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import * as model from './model.mjs';
const registry=new Map();class El{constructor(tag='div'){this.tag=tag;this.attrs={};this.style={};this.dataset={};this.children=[];this.textContent='';this.hidden=false;this.clientWidth=1100;this.clientHeight=800;this.classList={toggle(){}};this.listeners={};}setAttribute(k,v){this.attrs[k]=String(v);if(k==='id')registry.set(v,this);}append(...els){for(const e of els){this.children.push(e);if(e&&typeof e==='object')e.parent=this;}}replaceChildren(...els){this.children=[];this.append(...els);}querySelector(sel){return registry.get(sel.slice(1));}remove(){this.parent.children=this.parent.children.filter(e=>e!==this);}removeAttribute(k){delete this.attrs[k];}addEventListener(k,fn){this.listeners[k]=fn;}set src(v){this.attrs.src=v;}get src(){return this.attrs.src;}}
for(const id of ['canvas','stage','sizer','viewport','title','mode','empty','meta','base','roster','detail','connection','error','demo','empty-demo','live','preview','json','grid','coords','fit','minus','plus','full'])registry.set(id,new El());
const demo=JSON.parse(fs.readFileSync(new URL('./demo.json',import.meta.url))),idle={schema_version:1,active:false,revision:'idle'};
let scheduled=0;const ctx={...model,console,URLSearchParams,location:{search:''},setTimeout:()=>++scheduled,clearTimeout(){},ResizeObserver:class{observe(){}},document:{hidden:false,getElementById:id=>registry.get(id),createElement:tag=>new El(tag),createElementNS:(ns,tag)=>new El(tag),createTextNode:text=>({textContent:text}),addEventListener(){}},fetch:async url=>({ok:true,json:async()=>url==='demo.json'?demo:idle})};
vm.createContext(ctx);let code=fs.readFileSync(new URL('./app.js',import.meta.url),'utf8').replace(/^import .*?;\n/,'');code+='\nglobalThis.testing={render,get:()=>current};';vm.runInContext(code,ctx);await new Promise(r=>setImmediate(r));assert.equal(ctx.testing.get().active,false);
await registry.get('demo').onclick();assert.equal(registry.get('mode').textContent,'DEMO · KEIN KAMPAGNENSTAND');assert.equal(registry.get('tokens').children.length,7);assert.equal(registry.get('base').hidden,true);
const token=registry.get('tokens').children[0],terrain=registry.get('terrain').children[0],changed=structuredClone(demo);changed.revision='demo-2';changed.tokens[0].square='F7';ctx.testing.render(changed);assert.equal(registry.get('tokens').children[0],token);assert.equal(registry.get('terrain').children[0],terrain);assert.equal(token.style.transform,'translate(384px,448px)');
changed.tokens=changed.tokens.slice(1);ctx.testing.render(changed);assert.equal(registry.get('tokens').children.length,6);
registry.get('grid').onclick();assert.equal(registry.get('grid-layer').style.display,'none');registry.get('coords').onclick();assert.equal(registry.get('coords-layer').style.display,'none');
const legacy={schema_version:1,active:true,scene_id:'legacy',revision:'1',map:{width_px:640,height_px:480,asset:'maps/a.png',grid:{columns:10,rows:8,cell_px:{width:64,height:60},origin_px:{x:0,y:0}}},tokens:[]};ctx.testing.render(legacy);const imageSrc=registry.get('base').src;legacy.revision='2';ctx.testing.render(legacy);assert.equal(registry.get('base').src,imageSrc);
registry.get('json').value=JSON.stringify(demo);registry.get('preview').onclick();assert.equal(registry.get('mode').textContent,'LOKALE VORSCHAU');
console.log('PASS: idle/live startup, demo separation, SVG render, token DOM reuse, static terrain reuse, token removal, grid controls, unchanged image URL, JSON preview.');
